window.VITAMISSION_DATA = {
  vitamins: [
    { id: "A", name: "Vitamina A", scientific: "Retinoides y carotenoides provitamina A", type: "liposoluble", icon: "🥕", sources: "Hígado, huevos y lácteos; zanahoria, camote y hojas verdes aportan carotenoides que el cuerpo puede convertir.", absorption: "Se absorbe en el intestino junto con grasas y con ayuda de la bilis; los carotenoides pueden convertirse en retinol.", functions: "Participa directamente en el ciclo visual, la diferenciación celular y el mantenimiento de tejidos epiteliales.", deficiency: "La deficiencia puede causar dificultad para ver con poca luz y, en casos graves, xeroftalmia.", vision: "Relación directa: el retinal forma parte de los pigmentos visuales de la retina.", curious: "El color naranja de muchos vegetales se debe a carotenoides, algunos precursores de vitamina A.", quiz: "¿Qué función visual depende directamente de la vitamina A?", quizOptions: ["Participar en el ciclo visual", "Activar la coagulación", "Formar colágeno"], quizAnswer: 0 },
    { id: "D", name: "Vitamina D", scientific: "Calciferoles (D₂ y D₃)", type: "liposoluble", icon: "🐟", sources: "Pescados grasos, yema de huevo y alimentos fortificados. La piel también puede producirla con exposición solar.", absorption: "Se absorbe con grasa; luego se transforma en el hígado y los riñones en metabolitos activos.", functions: "Contribuye a la homeostasis del calcio y fósforo y a la salud ósea y muscular.", deficiency: "Puede causar raquitismo en niños y osteomalacia en adultos.", vision: "No es una vitamina con función directa establecida en el ciclo visual; no se debe inferir que suplementarla mejore la vista.", curious: "El cuerpo puede producir vitamina D en la piel, pero la cantidad varía según múltiples factores.", quiz: "¿Con qué nutriente trabaja estrechamente la vitamina D en la salud ósea?", quizOptions: ["Calcio", "Vitamina C", "Niacina"], quizAnswer: 0 },
    { id: "E", name: "Vitamina E", scientific: "Tocoferoles y tocotrienoles", type: "liposoluble", icon: "🌰", sources: "Aceites vegetales, semillas, frutos secos y germen de trigo.", absorption: "Se absorbe junto con lípidos de la dieta y se transporta en lipoproteínas.", functions: "Actúa como antioxidante liposoluble y ayuda a proteger las membranas celulares.", deficiency: "Es poco frecuente; en malabsorción grave puede afectar nervios y músculos.", vision: "Participa en la protección antioxidante general. No es el nutriente central del ciclo visual ni se debe prometer prevención de enfermedad ocular.", curious: "La vitamina E es un grupo de compuestos, no una molécula única.", quiz: "¿Cuál es una función reconocida de la vitamina E?", quizOptions: ["Antioxidante en membranas", "Formar pigmento visual por sí sola", "Ayudar a coagular la sangre"], quizAnswer: 0 },
    { id: "K", name: "Vitamina K", scientific: "Filoquinona (K₁) y menaquinonas (K₂)", type: "liposoluble", icon: "🥬", sources: "Verduras de hoja verde, brócoli y algunos aceites vegetales.", absorption: "Se absorbe con grasas de la dieta. Las bacterias intestinales producen algunas menaquinonas, pero no son una fuente garantizada suficiente.", functions: "Es cofactor para proteínas que participan en la coagulación y el metabolismo óseo.", deficiency: "Puede alterar la coagulación y aumentar el riesgo de sangrado.", vision: "No tiene un papel directo establecido en el ciclo visual.", curious: "La letra K se asocia históricamente con el término danés para coagulación.", quiz: "¿En qué proceso participa la vitamina K?", quizOptions: ["Coagulación sanguínea", "Visión con poca luz", "Conversión de glucosa en vitamina C"], quizAnswer: 0 },
    { id: "C", name: "Vitamina C", scientific: "Ácido ascórbico", type: "hidrosoluble", icon: "🍊", sources: "Cítricos, kiwi, pimiento, tomate y brócoli.", absorption: "Se absorbe en el intestino mediante transportadores; la absorción depende de la cantidad ingerida.", functions: "Participa en la síntesis de colágeno y mejora la absorción del hierro no hemo.", deficiency: "Una deficiencia grave y prolongada puede causar escorbuto.", vision: "Está presente en tejidos oculares y contribuye a funciones antioxidantes generales; eso no demuestra que suplementarla prevenga enfermedades oculares.", curious: "El calor y el almacenamiento prolongado pueden reducir la vitamina C de algunos alimentos.", quiz: "¿Qué estructura requiere vitamina C para sintetizar colágeno?", quizOptions: ["Tejido conectivo", "Pigmento de la retina", "Factor intrínseco"], quizAnswer: 0 },
    { id: "B6", name: "Vitamina B6", scientific: "Piridoxina, piridoxal y piridoxamina", type: "hidrosoluble", icon: "🍌", sources: "Pescado, aves, garbanzos, papas y plátano.", absorption: "Sus formas unidas a proteínas se liberan durante la digestión; se absorbe en el intestino delgado.", functions: "Participa en el metabolismo de aminoácidos, la síntesis de neurotransmisores y la formación de hemoglobina.", deficiency: "Es poco común; puede asociarse a anemia, dermatitis y alteraciones neurológicas.", vision: "No es un nutriente con papel directo establecido en el ciclo visual.", curious: "La vitamina B6 funciona como coenzima en numerosas reacciones metabólicas.", quiz: "¿En qué metabolismo participa especialmente la vitamina B6?", quizOptions: ["Aminoácidos", "Coagulación", "Absorción de luz por retinal"], quizAnswer: 0 },
    { id: "B12", name: "Vitamina B12", scientific: "Cobalaminas", type: "hidrosoluble", icon: "🥚", sources: "Carne, pescado, huevos y lácteos; también alimentos fortificados.", absorption: "Se une al factor intrínseco y se absorbe principalmente en el íleon terminal.", functions: "Es necesaria para la formación de glóbulos rojos y el funcionamiento neurológico.", deficiency: "Puede causar anemia megaloblástica y alteraciones neurológicas.", vision: "Una neuropatía óptica se ha descrito en deficiencias graves, pero los síntomas visuales tienen muchas causas y no permiten diagnosticarla.", curious: "Su absorción depende de una proteína producida en el estómago: el factor intrínseco.", quiz: "¿Qué ayuda a que B12 se absorba en el íleon?", quizOptions: ["Factor intrínseco", "Bilis solamente", "Vitamina K"], quizAnswer: 0 },
    { id: "B9", name: "Ácido fólico (B9)", scientific: "Folatos y ácido pteroilmonoglutámico", type: "hidrosoluble", icon: "🥦", sources: "Verduras de hoja verde, legumbres, cítricos y alimentos fortificados.", absorption: "Los folatos alimentarios se procesan durante la digestión y se absorben principalmente en el intestino delgado proximal.", functions: "Participa en la síntesis de ADN y la formación de células sanguíneas.", deficiency: "Puede causar anemia megaloblástica. Una ingesta insuficiente durante el embarazo se asocia con mayor riesgo de defectos del tubo neural.", vision: "No tiene un papel directo establecido en el ciclo visual.", curious: "El folato aparece de forma natural en alimentos; ácido fólico es la forma usada habitualmente en fortificación.", quiz: "¿Qué material celular requiere folato para sintetizarse?", quizOptions: ["ADN", "Retinal", "Bilis"], quizAnswer: 0 },
    { id: "B3", name: "Niacina (B3)", scientific: "Ácido nicotínico y nicotinamida", type: "hidrosoluble", icon: "🥜", sources: "Aves, pescado, cacahuates, legumbres y cereales fortificados.", absorption: "Se absorbe en el intestino delgado; el organismo también puede sintetizar parte a partir del triptófano.", functions: "Es precursora de NAD y NADP, coenzimas centrales en reacciones de energía celular.", deficiency: "La deficiencia grave puede causar pelagra, asociada con dermatitis, diarrea y alteraciones neurológicas.", vision: "No se presenta como una vitamina con efecto ocular directo demostrado en esta experiencia.", curious: "El organismo puede producir algo de niacina a partir de un aminoácido esencial.", quiz: "¿Qué coenzimas se forman a partir de niacina?", quizOptions: ["NAD y NADP", "ADN y ARN", "Retinal y rodopsina"], quizAnswer: 0 },
    { id: "B2", name: "Riboflavina (B2)", scientific: "Riboflavina", type: "hidrosoluble", icon: "🥛", sources: "Lácteos, huevos, carnes, almendras y algunos vegetales.", absorption: "Se libera de coenzimas durante la digestión y se absorbe en el intestino delgado.", functions: "Forma parte de FAD y FMN, coenzimas de reacciones de oxidación-reducción y metabolismo energético.", deficiency: "Puede causar queilosis, glositis y alteraciones en piel y mucosas.", vision: "Contribuye al mantenimiento de la visión normal mediante funciones metabólicas; no cumple el mismo papel directo en el ciclo visual que la vitamina A.", curious: "La riboflavina tiene un color amarillo intenso y puede dar fluorescencia.", quiz: "¿Qué coenzimas contienen riboflavina?", quizOptions: ["FAD y FMN", "NAD y NADP", "Factor intrínseco"], quizAnswer: 0 }
  ],
  questions: [
    { id: "food-k", category: "ALIMENTO", difficulty: "BÁSICO", question: "Has comido espinaca. ¿Qué vitamina destaca por su presencia en este alimento?", options: ["Vitamina K", "Vitamina B12", "Vitamina D"], answer: 0, explanation: "Las verduras de hoja verde, como la espinaca, son fuentes de vitamina K.", vitamin: "K" },
    { id: "food-c", category: "ALIMENTO", difficulty: "BÁSICO", question: "¿Qué alimento es una fuente conocida de vitamina C?", options: ["Naranja", "Mantequilla", "Arroz blanco"], answer: 0, explanation: "Los cítricos aportan vitamina C; también la contienen el kiwi, los pimientos y el brócoli.", vitamin: "C" },
    { id: "food-b12", category: "ALIMENTO", difficulty: "BÁSICO", question: "¿Cuál de estos alimentos puede aportar vitamina B12?", options: ["Huevo", "Zanahoria", "Aceite de oliva"], answer: 0, explanation: "La B12 está presente en alimentos de origen animal y en algunos alimentos fortificados.", vitamin: "B12" },
    { id: "abs-fat", category: "ABSORCIÓN", difficulty: "BÁSICO", question: "¿Cómo se absorben principalmente las vitaminas A, D, E y K?", options: ["Junto con las grasas de la dieta", "Solamente con agua", "No necesitan absorción"], answer: 0, explanation: "Son liposolubles: su absorción intestinal depende de procesos relacionados con los lípidos y las micelas.", vitamin: "A" },
    { id: "abs-b12", category: "ABSORCIÓN", difficulty: "AVANZADO", question: "¿Qué permite que la vitamina B12 se absorba en el íleon?", options: ["Su unión al factor intrínseco", "La vitamina C de la fruta", "La presencia de fibra"], answer: 0, explanation: "La B12 se une al factor intrínseco y el complejo se absorbe principalmente en el íleon terminal.", vitamin: "B12" },
    { id: "transport-c", category: "TRANSPORTE", difficulty: "INTERMEDIO", question: "Tras absorberse, ¿por dónde viajan muchas vitaminas hidrosolubles hacia los tejidos?", options: ["Por la sangre", "Por los huesos exclusivamente", "No se distribuyen por el cuerpo"], answer: 0, explanation: "Las vitaminas hidrosolubles absorbidas pasan a la circulación; cada nutriente tiene rutas y manejo propios.", vitamin: "C" },
    { id: "transport-lipo", category: "TRANSPORTE", difficulty: "AVANZADO", question: "¿Cómo circulan muchas vitaminas liposolubles después de su absorción intestinal?", options: ["En partículas lipídicas como quilomicrones", "Disueltas únicamente en saliva", "Unidas al oxígeno de los glóbulos rojos"], answer: 0, explanation: "Los lípidos absorbidos y vitaminas liposolubles se empaquetan en quilomicrones y pasan primero por la linfa.", vitamin: "E" },
    { id: "function-d", category: "FUNCIÓN", difficulty: "BÁSICO", question: "¿Qué mineral ayuda a utilizar la vitamina D para mantener huesos?", options: ["Calcio", "Hierro", "Yodo"], answer: 0, explanation: "La vitamina D contribuye a regular el calcio y el fósforo, importantes para la mineralización ósea.", vitamin: "D" },
    { id: "function-b2", category: "FUNCIÓN", difficulty: "INTERMEDIO", question: "¿Qué coenzimas contienen riboflavina (B2)?", options: ["FAD y FMN", "ADN y ARN", "Factor intrínseco"], answer: 0, explanation: "FAD y FMN son coenzimas derivadas de riboflavina que intervienen en reacciones celulares.", vitamin: "B2" },
    { id: "deficiency-a", category: "DEFICIENCIA", difficulty: "BÁSICO", question: "La dificultad para ver con poca luz puede relacionarse con una deficiencia de…", options: ["Vitamina A", "Vitamina K", "Vitamina B12"], answer: 0, explanation: "La vitamina A participa directamente en el ciclo visual. Este síntoma puede tener otras causas y no diagnostica una deficiencia.", vitamin: "A" },
    { id: "deficiency-c", category: "DEFICIENCIA", difficulty: "INTERMEDIO", question: "Una deficiencia grave y prolongada de vitamina C puede provocar…", options: ["Escorbuto", "Raquitismo", "Pelagra"], answer: 0, explanation: "El escorbuto se asocia a una deficiencia grave de vitamina C; la valoración de síntomas requiere profesionales de salud.", vitamin: "C" },
    { id: "challenge-b9", category: "DESAFÍO", difficulty: "AVANZADO", question: "¿Qué nutriente participa en la síntesis de ADN y es importante durante el desarrollo temprano?", options: ["Folato (B9)", "Vitamina K", "Vitamina E"], answer: 0, explanation: "El folato participa en la síntesis de ADN y la formación de células. Su carencia en el embarazo se asocia a defectos del tubo neural.", vitamin: "B9" },
    { id: "challenge-b3", category: "DESAFÍO", difficulty: "AVANZADO", question: "La pelagra se relaciona con una deficiencia grave de…", options: ["Niacina (B3)", "Vitamina D", "Vitamina K"], answer: 0, explanation: "La pelagra se asocia clásicamente a deficiencia grave de niacina; sus signos no deben autodiagnosticarse.", vitamin: "B3" },
    { id: "vision-a", category: "VISIÓN", difficulty: "BÁSICO", question: "¿Qué vitamina participa directamente en los pigmentos visuales de la retina?", options: ["Vitamina A", "Vitamina K", "Vitamina B9"], answer: 0, explanation: "El retinal, derivado de vitamina A, forma parte de pigmentos que permiten detectar la luz.", vitamin: "A" },
    { id: "vision-b2", category: "VISIÓN", difficulty: "INTERMEDIO", question: "¿Qué afirmación describe mejor a la riboflavina (B2) y la visión?", options: ["Contribuye a la visión normal mediante funciones metabólicas", "Reemplaza el papel de vitamina A en el ciclo visual", "Cura enfermedades oculares"], answer: 0, explanation: "B2 participa en procesos metabólicos y contribuye a mantener la visión normal; no reemplaza el papel directo de vitamina A.", vitamin: "B2" },
    { id: "true-lipo", category: "DESAFÍO", difficulty: "INTERMEDIO", question: "Verdadero o falso: los alimentos habituales ricos en vitaminas liposolubles causan toxicidad automáticamente.", options: ["Falso; los riesgos dependen de la vitamina y la exposición", "Verdadero; siempre son tóxicos", "Verdadero; cualquier verdura causa exceso"], answer: 0, explanation: "La toxicidad no es automática por comer alimentos habituales. Los riesgos varían y pueden aumentar con suplementos o exposiciones elevadas.", vitamin: "D" }
  ],
  board: [
    { category: "ALIMENTO", label: "Alimento", icon: "🍎", zone: "ALIMENTACIÓN" },
    { category: "ABSORCIÓN", label: "Absorción", icon: "🧪", zone: "ABSORCIÓN" },
    { category: "TRANSPORTE", label: "Transporte", icon: "🩸", zone: "TRANSPORTE" },
    { category: "FUNCIÓN", label: "Función", icon: "🧬", zone: "FUNCIÓN" },
    { category: "DEFICIENCIA", label: "Deficiencia", icon: "⚠️", zone: "FUNCIÓN", penalty: 2 },
    { category: "DESAFÍO", label: "Desafío", icon: "✦", zone: "FUNCIÓN", bonus: 50 },
    { category: "BONIFICACIÓN", label: "Bonificación", icon: "🎁", zone: "TRANSPORTE" },
    { category: "ALIMENTO", label: "Alimento", icon: "🥗", zone: "ALIMENTACIÓN" },
    { category: "ABSORCIÓN", label: "Absorción", icon: "🧪", zone: "ABSORCIÓN" },
    { category: "FUNCIÓN", label: "Función", icon: "🧬", zone: "FUNCIÓN" },
    { category: "VISIÓN", label: "Visión", icon: "👁️", zone: "VISIÓN" },
    { category: "VISIÓN", label: "Meta visual", icon: "🏁", zone: "VISIÓN", final: true }
  ]
};
